---
- name: add ether user
  user:
    name: "{{ geth_user }}"
    home: /var/lib/geth
    move_home: true

- name: "create {{ geth_user }} build dir"
  become_user: "{{ geth_user }}"
  file:
    path: "~{{ geth_user }}/build/"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    state: directory

- name: create geth extraction dir
  become_user: "{{ geth_user }}"
  file:
    path: "~{{ geth_user }}/build/geth"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    state: directory

- name: download geth
  become_user: "{{ geth_user }}"
  register: download_geth
  get_url:
    url: "https://gethstore.blob.core.windows.net/builds/{{ geth_build }}.tar.gz"
    dest: "~{{ geth_user }}/build/{{ geth_build }}.tar.gz"
    mode: 0644
    checksum: "{{ geth_checksum }}"

- name: extract geth tarball
  become_user: "{{ geth_user }}"
  when: download_geth.changed
  unarchive:
    remote_src: yes
    src: "~{{ geth_user }}/build/{{ geth_build }}.tar.gz"
    dest: "~{{ geth_user }}/build/"

- name: create .local/bin
  become_user: "{{ geth_user }}"
  file:
    path: "~{{ geth_user }}/.local/bin"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    state: directory

- name: ensure geth service stopped before copy
  when: download_geth.changed
  shell: "[[ -e /lib/systemd/system/geth.service ]] && sudo systemctl stop geth"
  ignore_errors: yes

- name: put geth executable in ~/.local/bin
  when: download_geth.changed
  become_user: "{{ geth_user }}"
  shell: "cp ~{{ geth_user }}/build/{{ geth_build }}/geth ~{{ geth_user }}/.local/bin/geth"

- name: update ether's environment
  become_user: "{{ geth_user }}"
  script: "../files/addpath.sh ~{{ geth_user }}/.local/bin"

- name: create /etc/geth
  file:
    path: "/etc/geth"
    owner: "{{ geth_user }}"
    group: "{{ geth_user }}"
    state: directory

- name: Ensure passwords file is correct
  template: src=passwords.txt.j2 dest="/etc/geth/passwords.txt" owner=root group="ether" mode=0640

- name: create .ethereum
  file:
    state: directory
    path: ~{{ geth_user }}/.ethereum
    owner: ether
    group: ether
    mode: 0750

# - name: check firewalld availability
#   shell: firewall-cmd --state
#   register: firewall_state
#   ignore_errors: true

- name: create geth directory
  file:
    state: directory
    path: "{{ geth_data_dir }}"
    owner: ether
    group: ether
    mode: 0755

- name: symlink chaindata to /data
  file:
    state: link
    path: ~{{ geth_user }}/.ethereum/geth
    src: "{{ geth_data_dir }}"

- name: install geth config file
  register: geth_config
  template:
    src: ../templates/geth.toml.j2
    dest: /etc/geth/geth.toml
    owner: root
    group: ether
    mode: 0644

- name: install service file
  register: geth_service
  template:
    src: ../templates/geth.service
    dest: /lib/systemd/system/geth.service
    owner: root
    group: root
    mode: 0644

- name: reload systemd
  when: geth_service.changed
  shell: systemctl daemon-reload

- name: ensure geth service started
  when: geth_service.changed or geth_config.changed
  service: 
    name: geth
    state: restarted

# Checks for an account.  1 for no accounts, 0 for accounts found
- name: check for an account
  become_user: "{{ geth_user }}"
  shell: geth account list 2>&1 | grep "No etherbase" | wc -l
  register: account_check

# - name: if no account, create one
#   shell: "geth account create --datadir {{ geth_data_dir }} --password /etc/geth/passwords.txt"
#   #when: geth_etherbase_password is defined and account_check.stdout == 1

- name: ensure RPC access allowed
  firewalld:
    state: enabled
    zone: public
    port: "{{ geth_rpcport }}/tcp"
    permanent: true
  when: geth_rpcport is defined and geth_rpcpublic == true and firewall_state.stdout == 'running'
